language: 
  - java
jdk: 
  - oraclejdk8
  - oraclejdk7
before_install: 
  - sudo apt-get update
  - sudo apt-get install libaudit-dev auditd libfuse-dev fuse pkg-config
script: 
  - ./configure;
  - make
  - sudo make install
notifications:
  email:
    - hasanatkazmi@gmail.com
    - hassaan.irshad@sri.com
